/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimpleDSLScopeProvider extends DelegatingScopeProvider {
}
