/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.senacor.com.smt.dsl.SimpleDSLRuntimeModule;
import de.senacor.com.smt.dsl.SimpleDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SimpleDSLIdeSetup extends SimpleDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SimpleDSLRuntimeModule(), new SimpleDSLIdeModule()));
	}
	
}
