/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SimpleDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.Document");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDocumentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cEntitesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEntitesEntityParserRuleCall_3_0 = (RuleCall)cEntitesAssignment_3.eContents().get(0);
		
		//Document:
		//	{Document}
		//	'package' name=EString
		//	entites+=Entity*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Document} 'package' name=EString entites+=Entity*
		public Group getGroup() { return cGroup; }
		
		//{Document}
		public Action getDocumentAction_0() { return cDocumentAction_0; }
		
		//'package'
		public Keyword getPackageKeyword_1() { return cPackageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//entites+=Entity*
		public Assignment getEntitesAssignment_3() { return cEntitesAssignment_3; }
		
		//Entity
		public RuleCall getEntitesEntityParserRuleCall_3_0() { return cEntitesEntityParserRuleCall_3_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Keyword cFullStopKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//QualifiedName:
		//	(ID '.')* ID;
		@Override public ParserRule getRule() { return rule; }
		
		//(ID '.')* ID
		public Group getGroup() { return cGroup; }
		
		//(ID '.')*
		public Group getGroup_0() { return cGroup_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0_0() { return cIDTerminalRuleCall_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_0_1() { return cFullStopKeyword_0_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFieldsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cFieldsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cFieldsFieldParserRuleCall_4_2_0 = (RuleCall)cFieldsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cFieldsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cFieldsFieldParserRuleCall_4_3_1_0 = (RuleCall)cFieldsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRelationshipsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRelationshipsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRelationshipsRelationshipParserRuleCall_5_2_0 = (RuleCall)cRelationshipsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRelationshipsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRelationshipsRelationshipParserRuleCall_5_3_1_0 = (RuleCall)cRelationshipsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Entity:
		//	{Entity}
		//	'Entity'
		//	name=EString
		//	'{' ('fields' '{' fields+=Field ("," fields+=Field)* '}')? ('relationships' '{' relationships+=Relationship (','
		//	relationships+=Relationship)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Entity} 'Entity' name=EString '{' ('fields' '{' fields+=Field ("," fields+=Field)* '}')? ('relationships' '{'
		//relationships+=Relationship (',' relationships+=Relationship)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Entity}
		public Action getEntityAction_0() { return cEntityAction_0; }
		
		//'Entity'
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('fields' '{' fields+=Field ("," fields+=Field)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'fields'
		public Keyword getFieldsKeyword_4_0() { return cFieldsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//fields+=Field
		public Assignment getFieldsAssignment_4_2() { return cFieldsAssignment_4_2; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_2_0() { return cFieldsFieldParserRuleCall_4_2_0; }
		
		//("," fields+=Field)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//fields+=Field
		public Assignment getFieldsAssignment_4_3_1() { return cFieldsAssignment_4_3_1; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_3_1_0() { return cFieldsFieldParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('relationships' '{' relationships+=Relationship (',' relationships+=Relationship)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'relationships'
		public Keyword getRelationshipsKeyword_5_0() { return cRelationshipsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//relationships+=Relationship
		public Assignment getRelationshipsAssignment_5_2() { return cRelationshipsAssignment_5_2; }
		
		//Relationship
		public RuleCall getRelationshipsRelationshipParserRuleCall_5_2_0() { return cRelationshipsRelationshipParserRuleCall_5_2_0; }
		
		//(',' relationships+=Relationship)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//','
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//relationships+=Relationship
		public Assignment getRelationshipsAssignment_5_3_1() { return cRelationshipsAssignment_5_3_1; }
		
		//Relationship
		public RuleCall getRelationshipsRelationshipParserRuleCall_5_3_1_0() { return cRelationshipsRelationshipParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeDataTypeEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLengthKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLengthAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLengthINTTerminalRuleCall_5_1_0 = (RuleCall)cLengthAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPrecisionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPreciscionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPreciscionINTTerminalRuleCall_6_1_0 = (RuleCall)cPreciscionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cScaleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cScaleAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cScaleINTTerminalRuleCall_7_1_0 = (RuleCall)cScaleAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Field:
		//	{Field}
		//	'Field' name=EString '{' ('Type' type=DataType)? ('Length' length=INT)? ('Precision' preciscion=INT)? ('Scale'
		//	scale=INT)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Field} 'Field' name=EString '{' ('Type' type=DataType)? ('Length' length=INT)? ('Precision' preciscion=INT)? ('Scale'
		//scale=INT)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Field}
		public Action getFieldAction_0() { return cFieldAction_0; }
		
		//'Field'
		public Keyword getFieldKeyword_1() { return cFieldKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('Type' type=DataType)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=DataType
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//DataType
		public RuleCall getTypeDataTypeEnumRuleCall_4_1_0() { return cTypeDataTypeEnumRuleCall_4_1_0; }
		
		//('Length' length=INT)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Length'
		public Keyword getLengthKeyword_5_0() { return cLengthKeyword_5_0; }
		
		//length=INT
		public Assignment getLengthAssignment_5_1() { return cLengthAssignment_5_1; }
		
		//INT
		public RuleCall getLengthINTTerminalRuleCall_5_1_0() { return cLengthINTTerminalRuleCall_5_1_0; }
		
		//('Precision' preciscion=INT)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'Precision'
		public Keyword getPrecisionKeyword_6_0() { return cPrecisionKeyword_6_0; }
		
		//preciscion=INT
		public Assignment getPreciscionAssignment_6_1() { return cPreciscionAssignment_6_1; }
		
		//INT
		public RuleCall getPreciscionINTTerminalRuleCall_6_1_0() { return cPreciscionINTTerminalRuleCall_6_1_0; }
		
		//('Scale' scale=INT)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'Scale'
		public Keyword getScaleKeyword_7_0() { return cScaleKeyword_7_0; }
		
		//scale=INT
		public Assignment getScaleAssignment_7_1() { return cScaleAssignment_7_1; }
		
		//INT
		public RuleCall getScaleINTTerminalRuleCall_7_1_0() { return cScaleINTTerminalRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RelationshipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.Relationship");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelationshipAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelationshipKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cToEntityAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cToEntityEntityCrossReference_5_0 = (CrossReference)cToEntityAssignment_5.eContents().get(0);
		private final RuleCall cToEntityEntityQualifiedNameParserRuleCall_5_0_1 = (RuleCall)cToEntityEntityCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Relationship:
		//	{Relationship}
		//	'Relationship' name=EString '{'
		//	'to' toEntity=[Entity|QualifiedName]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Relationship} 'Relationship' name=EString '{' 'to' toEntity=[Entity|QualifiedName] '}'
		public Group getGroup() { return cGroup; }
		
		//{Relationship}
		public Action getRelationshipAction_0() { return cRelationshipAction_0; }
		
		//'Relationship'
		public Keyword getRelationshipKeyword_1() { return cRelationshipKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'to'
		public Keyword getToKeyword_4() { return cToKeyword_4; }
		
		//toEntity=[Entity|QualifiedName]
		public Assignment getToEntityAssignment_5() { return cToEntityAssignment_5; }
		
		//[Entity|QualifiedName]
		public CrossReference getToEntityEntityCrossReference_5_0() { return cToEntityEntityCrossReference_5_0; }
		
		//QualifiedName
		public RuleCall getToEntityEntityQualifiedNameParserRuleCall_5_0_1() { return cToEntityEntityQualifiedNameParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	public class DataTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.senacor.com.smt.dsl.SimpleDSL.DataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRINGSTRINGKeyword_0_0 = (Keyword)cSTRINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNUMBEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNUMBERNUMBERKeyword_1_0 = (Keyword)cNUMBEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDATEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDATEDATEKeyword_2_0 = (Keyword)cDATEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum DataType:
		//	STRING | NUMBER | DATE;
		public EnumRule getRule() { return rule; }
		
		//STRING | NUMBER | DATE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_0() { return cSTRINGEnumLiteralDeclaration_0; }
		
		//'STRING'
		public Keyword getSTRINGSTRINGKeyword_0_0() { return cSTRINGSTRINGKeyword_0_0; }
		
		//NUMBER
		public EnumLiteralDeclaration getNUMBEREnumLiteralDeclaration_1() { return cNUMBEREnumLiteralDeclaration_1; }
		
		//'NUMBER'
		public Keyword getNUMBERNUMBERKeyword_1_0() { return cNUMBERNUMBERKeyword_1_0; }
		
		//DATE
		public EnumLiteralDeclaration getDATEEnumLiteralDeclaration_2() { return cDATEEnumLiteralDeclaration_2; }
		
		//'DATE'
		public Keyword getDATEDATEKeyword_2_0() { return cDATEDATEKeyword_2_0; }
	}
	
	private final DocumentElements pDocument;
	private final EStringElements pEString;
	private final QualifiedNameElements pQualifiedName;
	private final EntityElements pEntity;
	private final FieldElements pField;
	private final RelationshipElements pRelationship;
	private final DataTypeElements eDataType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SimpleDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDocument = new DocumentElements();
		this.pEString = new EStringElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pEntity = new EntityElements();
		this.pField = new FieldElements();
		this.pRelationship = new RelationshipElements();
		this.eDataType = new DataTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.senacor.com.smt.dsl.SimpleDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Document:
	//	{Document}
	//	'package' name=EString
	//	entites+=Entity*;
	public DocumentElements getDocumentAccess() {
		return pDocument;
	}
	
	public ParserRule getDocumentRule() {
		return getDocumentAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//QualifiedName:
	//	(ID '.')* ID;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//Entity:
	//	{Entity}
	//	'Entity'
	//	name=EString
	//	'{' ('fields' '{' fields+=Field ("," fields+=Field)* '}')? ('relationships' '{' relationships+=Relationship (','
	//	relationships+=Relationship)* '}')?
	//	'}';
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//Field:
	//	{Field}
	//	'Field' name=EString '{' ('Type' type=DataType)? ('Length' length=INT)? ('Precision' preciscion=INT)? ('Scale'
	//	scale=INT)?
	//	'}';
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//Relationship:
	//	{Relationship}
	//	'Relationship' name=EString '{'
	//	'to' toEntity=[Entity|QualifiedName]
	//	'}';
	public RelationshipElements getRelationshipAccess() {
		return pRelationship;
	}
	
	public ParserRule getRelationshipRule() {
		return getRelationshipAccess().getRule();
	}
	
	//enum DataType:
	//	STRING | NUMBER | DATE;
	public DataTypeElements getDataTypeAccess() {
		return eDataType;
	}
	
	public EnumRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
