/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl.ui.tests;

import com.google.inject.Injector;
import de.senacor.com.smt.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SimpleDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("de.senacor.com.smt.dsl.SimpleDSL");
	}

}
