/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleDSLRuntimeModule extends AbstractSimpleDSLRuntimeModule {
}
