/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimpleDSLStandaloneSetup extends SimpleDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new SimpleDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
