/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimpleDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/senacor/com/smt/dsl/parser/antlr/internal/InternalSimpleDSL.tokens");
	}
}
