/*
 * generated by Xtext 2.20.0
 */
package de.senacor.com.smt.dsl.parser.antlr;

import com.google.inject.Inject;
import de.senacor.com.smt.dsl.parser.antlr.internal.InternalSimpleDSLParser;
import de.senacor.com.smt.dsl.services.SimpleDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimpleDSLParser extends AbstractAntlrParser {

	@Inject
	private SimpleDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleDSLParser createParser(XtextTokenStream stream) {
		return new InternalSimpleDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public SimpleDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
